### ISSUE TITLE
A less verbose, more efficient way to iterate over JsonObject (key, value, comment) triples, and JsonArray (value, comment) pairs

### ISSUE THREAD

**Issue by Barteks2x** [falkreon/Jankson#24]
Currently if I want to iterate over all the data in a `JsonObject` I have to do this:

```java
for (Map.Entry<String, JsonElement> entry : object.entrySet()) {
    String comment = object.getComment(entry.getKey());
    // do things
}
```
Which is not only unnecessarily verbose, but also not very efficient.
Iterating over JsonArray isn't that inefficient, but still quite verbose:
```java
for (int i = 0; i < array.size(); i++) {
    JsonElement element = newArr.get(i);
    String comment = newArr.getComment(i);
    // do things
}
```

Would be very useful to have something a bit less verbose and more efficient, maybe even a `forEach` method.

**Comment by falkreon** [comment]
Huh. Well for starters:
```java
for(JsonElement elem : array) {
    /* something */
}
```
JsonArray has always supported `Collection<JsonElement>` (and Iterable), as of 1.2.0 it supports `List` (and ListIterable). Which means there's also automatically a .forEach

JsonObject also has a .forEach, since it implements `Map<String, JsonElement>`.

Comments are headed for a bit of reorganizing, since "comment attribution" has always been kind of a dicey proposition if it's not coming directly from the annotations on an object. It's probably going to evolve into something like `getCommentBefore(key)` or a specific file-structural view in addition to the List/Map view. I think it's going to be a while before that design's finished.

**Comment by Barteks2x** [comment]
Yes, I know I can do what you said, but it doesn't at all handle comments. I'm writing code that updates and merges my json files, in a way that attempts to preserve comments and order. This requires quite a bit of `getComment` and `setComment` and iterating over all entries.

**Comment by falkreon** [comment]
`putDefault` might help.

Working the X/Y problem, I'd *love* to make a one-stop method to pour a POJO into a JsonObject with comments as defaults, but that'll only work if I add some kind of `@Category` annotation that lets jankson know it can recurse into subnodes.

**Comment by Barteks2x** [comment]
`putDefault` doesn't really solve any significant part of what I'm trying to do and definitely doesn't reduce the need for what I originally said here.

So to put into context what it is that I'm doing:
I'm using json as a format for Minecraft world generation customization 9similar to how it's done for "customized" worle type, but more). I already have several old versions of the json that existed, and I'm just adding more features now, with yet more changes.
Because trying to write one giant deserializer that handles all the possible cases would be quite challenging and very hard to maintain, I now mark each one with version, and create a converter from each older version to the next. The intent is that the conversion will preserve as much of the user structure and comments as possible. This already involves quite a lot of work, especially since I don't want to actually modify the input json object and inctead create a new modified copy (it would significantly complicate the conversion process if I just modified existing one). Because of quirks of some of the old formats, I actually need to effectively merge 2 json objects, the main one and a "parent" that contains default values (with some exceptions for values from data that existed before I allowed nesting them). My implementation also attempts to turn unrecognized values into comments, instead of discarding them.

Second part of what I'm doing is, being able to deserialize the json into the target object, and then turn it back into config json (potentially with modifications) without losing comments and ordering information (I may be able to remove large part of why I need it by rewriting parts of my GUI code to deal with JsonObject directly, but I still need to somehow deal with arrays anyway). This also involves json arrays, where I also want to preserve as much information as possible (that turns out to be quite a challenging task). All that involves a lot of work manipulating JsonElement, JsonObject and JsonArray.

At this point I have most of the implementation done and tested, but the code is quite verbose, not very efficient and not easy to read due to all the extra noise needed to make use of this library.

**Comment by falkreon** [comment]
I mentioned earlier that "comment attribution" is a dicey proposition. Here's what I mean:

```json5
{
    /* this comment probably belongs to the key 'foo' */
    'foo': 5 // this comment probably also belongs to the key 'foo'
}
```

Or worse,
```json5
{
    'foo': 5, //foo and bar are
    'bar': 4  //stored in the baz
}
```

This currently causes serialization-deserialization to exhibit some morbid behavior, and has me rethinking whether it's a valid concept to attribute a comment to a key. If I can't, then comments exist more file-structurally either at the end of key-value pair lines, or "between" keys rather than "at" keys, and in the latter, more common case, don't "belong" to keys at all. So unfortunately I feel like I need to answer these questions before I answer this one.

**Comment by falkreon** [comment]
Closing the *issue* for now because we just don't have the design pinned down, but this is still an important goal. Going forward I'd like to continue talking about this in Discussions and hopefully come up with a plan that can be implemented.
