### ISSUE TITLE
MC version is 1.14.3, despite the fact that multiple mods in a different version require Jankson?

### ISSUE THREAD

**Issue by dvult** [falkreon/Jankson#43]
I dun really no if this is the same thing as the minecraft mod on curseforge, and i'm sorry for taking your time if it's not, but I just really wanted to know why it was so.

**Comment by falkreon** [comment]
I apologise for the confusion. Short answer is that if you're not writing a mod, you don't have to worry about it because it's already in the jar of the mods that use it, even when it shows up as a dependency.

Long answer, what you're talking about is Jankson-Fabric ( https://github.com/CottonMC/Jankson-Fabric ) which takes this library and makes a canonical API version available for each version of Minecraft in a way where it can be "included", where it's already inside the jar and Fabric can easily figure out version disputes.

If I hadn't made a "mod version" of the library, and pinned an API version to each minecraft version, I'm fairly certain that some breaking changes would have resulted in some dependency hell over on the minecraft side of things. As it is, you can just trust the jars to have the jankson you need.

**Comment by dvult** [comment]
I see, thanks!
