### ISSUE TITLE
Help with using hjson

### ISSUE THREAD

**Issue by joshcangit** [falkreon/Jankson#59]
I need help.
Not sure how to create and write a hjson file with comment.
Not sure if this reads from `JsonObject` or `LinkedHashMap` to get a value.

I've tried practicing with other libraries like `java.nio` for reading/writing and `com.google.code.gson` for JSON but still not confident.

**Comment by falkreon** [comment]
There are two ways to get data from your program into an (h)json file. The first is to start from a JsonObject as you've suggested:

```java
JsonObject testObject = new JsonObject(); //This will represent the whole file
testObject.put("foo", JsonPrimitive.of(12), "This is a comment");

//Set up the destination file
File destFile = new File("test.hjson");
// I highly recommend using utf8 for all character data you handle.
try (FileWriter writer = new FileWriter(destFile, StandardCharsets.UTF_8)) {

  //Write the data out
  testObject.toJson(writer, JsonGrammar.JSON5, 0);
  //Try-with-resources will close the writer here
} catch (IOException ex) {
  ex.printStackTrace();
}
```

If you want different quirks you can take a look at JsonGrammar - there's no prebaked grammar object for hjson since it's somewhat nonstandard and json5 is more or less a superset at this point, but you could build an hjson grammar if that was an important part of this.

Another way would be to take your domain object (whatever object stores your data when it's not a JsonObject or a file) and store it directly. For this we use the Marshaller in Jankson, which is responsible for converting objects between different types.

```java
SomeObject someObjectDefinedEarlier = new SomeObject();

Jankson jankson = Jankson.builder().build();
JsonElement elem = jankson.toJson(someObjectDefinedEarlier);
//Here you might want to check and throw if !(elem instanceof JsonObject)
//otherwise you might not get what you expect

//This part might look familiar
File destFile = new File("test.json");
try (FileWriter writer = new FileWriter(destFile, StandardCharsets.UTF_8)) {

  testObject.toJson(writer, JsonGrammar.JSON5, 0);

} catch (IOException ex) {
  ex.printStackTrace();
}
```

where SomeObject is something like
```java
public class SomeObject {
  transient int bar = 8192; //transient fields are not serialized
  public static String bux = "a"; //static fields are not serialized
  
  //the Comment annotation is picked up by Jankson and added to the json in toJson()
  @Comment("This is a comment")
  private int foo = 42; //private fields ARE serialized.
}
```

Some people like this second method because they can avoid having any intermediate formats, but it means that the file and the live data have to have the same schema - they need to look very similar.

**Comment by joshcangit** [comment]
Ok, thanks. Now I know how to write to file. Just needed to import the right libraries.

Now, I'm wondering if there is a function to process a `Reader` or `BufferedReader`.

**Comment by joshcangit** [comment]
I'm closing this and a link to my gist.
[JanksonExample.java](https://gist.github.com/joshcangit/5be3e87832e7e3d78367f6c546e5eec1)

**Comment by falkreon** [comment]
using toString will probably enclose the value in quotes, which you don't want. If you've got a JsonPrimitive or JsonElement from get, use `asString()` to get its raw value as a String.

But you almost definitely want to use the marshalled get instead: `String foo = someObject.get(String.class, "foo");`
If I was to add a `getString` it would just be a convenience method for this.

**Comment by joshcangit** [comment]
> If you want different quirks you can take a look at JsonGrammar - there's no prebaked grammar object for hjson since it's somewhat nonstandard and json5 is more or less a superset at this point, but you could build an hjson grammar if that was an important part of this.

Yes, my example does have hjson grammar.
It'd be nice to have it prebaked but maybe after you've completed support for multiline strings.
